## 목표 : 선형 모델기반의 분류 모델 구현
- 데이터 : sklearn.datasets 의 iris
- 피쳐 : 2개
- 타켓 : 3개


### (1) 모듈 로딩
<hr>

In [50]:

from sklearnex import patch_sklearn, unpatch_sklearn
patch_sklearn()

import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
# 나눔고딕
mpl.rc('font', family='NanumGothic')
import seaborn as sns
import scipy.stats as stats
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
from sklearn.pipeline import Pipeline



Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)


In [51]:
# 데이터 로딩 => Bunrch 타입으로 dict와 유사한 scikit-learn 클래스
df = load_iris(as_frame=True)['frame']
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
145       2  
146       2  
147       2  
148       2  
149       2

In [52]:
df['target'].unique()

array([0, 1, 2])

### (2) 모델 학습 진행
<hr>


In [53]:
X = df.drop(['target'], axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y, 
    train_size=0.8, 
    random_state=42
)

X_train.shape, X_test.shape

((120, 4), (30, 4))

In [54]:
from sklearn.preprocessing import StandardScaler, RobustScaler
from sklearn.linear_model import LogisticRegressionCV
model = Pipeline(
    steps=[
        ('scaler', StandardScaler()),
        ('iqrscaler', RobustScaler()),
        ('logistic', LogisticRegression(max_iter=1000)),
        
    ]
)
model = LogisticRegression(max_iter=1000)
model

LogisticRegression(max_iter=1000)

In [58]:
model.fit(X_train, y_train)
model.score(X_test, y_test)


1.0

In [56]:
print(model.classes_)
print(model.feature_names_in_)
# for x in dir(model):
#     if x.find('__')<0:
#         try:
#             print(getattr(model, x)())
#         except: print(getattr(model, x))
print(model.n_iter_)

[0 1 2]
['sepal length (cm)' 'sepal width (cm)' 'petal length (cm)'
 'petal width (cm)']
[93]


In [57]:
model.predict([df.iloc[80,:-1]])

c:\Users\Administrator\anaconda3\envs\EXAM_ML\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])

#### (2-1) 2개의 데이터만 추출

In [64]:
df_only2 = df[df['target'].isin([1,2])]
X_train, X_test, y_train, y_test = train_test_split(
    df_only2.drop(['target'], axis=1),
    df_only2['target'],
    train_size=0.8,
    random_state=42
)
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [67]:
model.predict(X_test)
for command in dir(model):
    if command.find('__')<0:
        try:
            print(getattr(model, command)())
        except:
            print(getattr(model, command))

1.0
<bound method _MetadataRequester._build_request_for_signature of <class 'daal4py.sklearn.linear_model.logistic_path.LogisticRegression'>>
<bound method BaseEstimator._check_feature_names of LogisticRegression(max_iter=1000)>
<bound method BaseEstimator._check_n_features of LogisticRegression(max_iter=1000)>
sklearn
https://scikit-learn.org/1.4/modules/generated/{estimator_module}.{estimator_name}.html
None
classifier
{'fit': {'sample_weight': None}, 'score': {'sample_weight': None}}

{'fit': {'sample_weight': None}, 'score': {'sample_weight': None}}
['C', 'class_weight', 'dual', 'fit_intercept', 'intercept_scaling', 'l1_ratio', 'max_iter', 'multi_class', 'n_jobs', 'penalty', 'random_state', 'solver', 'tol', 'verbose', 'warm_start']
{'array_api_support': False, 'non_deterministic': False, 'requires_positive_X': False, 'requires_positive_y': False, 'X_types': ['2darray'], 'poor_score': False, 'no_validation': False, 'multioutput': False, 'allow_nan': False, 'stateless': False, 'multi

AttributeError: 'LogisticRegression' object has no attribute 'feature_names_in_'