## 목표 : 선형 모델기반의 분류 모델 구현
- 데이터 : sklearn.datasets 의 iris
- 피쳐 : 2개
- 타켓 : 3개


### (1) 모듈 로딩
<hr>

In [1]:

from sklearnex import patch_sklearn, unpatch_sklearn
patch_sklearn()

import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
# 나눔고딕
mpl.rc('font', family='NanumGothic')
import seaborn as sns
import scipy.stats as stats
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
from sklearn.pipeline import Pipeline



Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)


In [2]:
# 데이터 로딩 => Bunrch 타입으로 dict와 유사한 scikit-learn 클래스
df = load_iris(as_frame=True)['frame']
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
145       2  
146       2  
147       2  
148       2  
149       2

In [3]:
df['target'].unique()

array([0, 1, 2])

### (2) 모델 학습 진행
<hr>


In [4]:
X = df.drop(['target'], axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y, 
    train_size=0.8, 
    random_state=42
)

X_train.shape, X_test.shape

((120, 4), (30, 4))

In [5]:
from sklearn.preprocessing import StandardScaler, RobustScaler
from sklearn.linear_model import LogisticRegressionCV
model = Pipeline(
    steps=[
        ('scaler', StandardScaler()),
        ('iqrscaler', RobustScaler()),
        ('logistic', LogisticRegression(max_iter=1000)),
        
    ]
)
model = LogisticRegression(max_iter=1000)
model

LogisticRegression(max_iter=1000)

In [6]:
model.fit(X_train, y_train)
model.score(X_test, y_test)


1.0

In [7]:
print(model.classes_)
print(model.feature_names_in_)
# for x in dir(model):
#     if x.find('__')<0:
#         try:
#             print(getattr(model, x)())
#         except: print(getattr(model, x))
print(model.n_iter_)

[0 1 2]
['sepal length (cm)' 'sepal width (cm)' 'petal length (cm)'
 'petal width (cm)']
[92]


In [8]:
model.predict([df.iloc[80,:-1]])

c:\Users\Administrator\anaconda3\envs\EXAM_ML\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])

#### (2-1) 2개의 데이터만 추출

In [9]:
df_only2 = df[df['target'].isin([1,2])]
# X_train, X_test, y_train, y_test = train_test_split(
#     df_only2.drop(['target'], axis=1),
#     df_only2['target'],
#     train_size=0.8,
#     random_state=42
# )
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [10]:
model.predict(X_test)
model.coef_

array([[-0.39685059,  0.96060163, -2.37370679, -1.00382407],
       [ 0.5126652 , -0.25356069, -0.21556709, -0.7688234 ],
       [-0.1158146 , -0.70704094,  2.58927388,  1.77264747]])

In [11]:
model.feature_names_in_

array(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'], dtype=object)

In [12]:
model._get_param_names()

['C',
 'class_weight',
 'dual',
 'fit_intercept',
 'intercept_scaling',
 'l1_ratio',
 'max_iter',
 'multi_class',
 'n_jobs',
 'penalty',
 'random_state',
 'solver',
 'tol',
 'verbose',
 'warm_start']

[OvA/OvR] ==> 3개 모델  


setosa : Setosa VS 나머지(Versicolor,Virginica)  
Versicolor : Versicolor VS 나머지(Setosa,Virginica)  
Virginica : Virginica VS 나머지(Setosa,Versicolor)  


[OvO] ==> 3 * 2 / 2 = 3개  
Setosa vs Versicolor
Setosa vs Virginica
Versicolor vs Virginica

In [13]:
for x in dir(model):
    if x.find('name') >= 0:
        print(x)

_check_feature_names
_get_param_names
feature_names_in_


In [17]:
from pycaret.classification import *
s = setup(data = df_only2, target = 'target', session_id=10)


In [18]:
s.compare_models()

RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=10, solver='auto',
                tol=0.0001)